from __future__ import annotations

from .viewer_gif import GIF_SCRIPT

LIVE_SCRIPT_D = r"""
(()=>{
const core=window.__execweaveCore;
if(!core)return;
const structuredList=document.getElementById('activity-list'),rawLog=document.getElementById('raw-log'),rawRows=document.getElementById('raw-rows'),activityCount=document.getElementById('activity-count'),filterGroup=document.querySelector('.filter-group'),finishedActions=document.getElementById('finished-actions'),replayButton=document.getElementById('replay-run'),gifButton=document.getElementById('download-gif'),openFinalButton=document.getElementById('open-final'),details=document.getElementById('details'),detailsEmpty=document.getElementById('details-empty');
const MAX_RAW=640;
let rawEntries=[],logMode='structured',finishedShown=false,finalHtmlCache=null,replaying=false;
function rawId(entry){return`raw-${entry.stream||'events'}-${entry.line??'x'}-${entry.event?.event_id||entry.event?.sequence||''}`}
function rawTime(event){const value=event?.timestamp;if(!value)return'—';const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3})}
function rawEventType(event){return String(event?.event_type||event?.type||'event')}
function rawRelation(event){return String(event?.relation||'—')}
function rawSummary(event){try{return JSON.stringify(event)}catch(_){return String(event)}}
function setRawEntries(items){rawEntries=(items||[]).slice(-MAX_RAW);renderRaw(false)}
function addRawEntries(items){if(!items?.length)return;rawEntries.push(...items);if(rawEntries.length>MAX_RAW)rawEntries=rawEntries.slice(-MAX_RAW);renderRaw(logMode==='raw')}
function findGraphEdge(event){const source=event?.source?.id,target=event?.target?.id,relation=event?.relation;if(!source||!target||!relation)return null;const visible=[...document.querySelectorAll('.edge')].find(el=>el.dataset.source===source&&el.dataset.target===target&&el.dataset.relation===String(relation).toLowerCase());return visible?.dataset.edgeId||null}
function showRaw(entry){const event=entry.event||{};detailsEmpty.hidden=true;details.innerHTML='';const title=document.createElement('div');title.className='current-title';title.textContent=rawEventType(event);const sub=document.createElement('div');sub.className='current-sub';sub.textContent=`${entry.stream||'events.jsonl'} line ${entry.line??'—'} · ${rawRelation(event)}`;const pre=document.createElement('pre');pre.textContent=JSON.stringify(event,null,2);const raw=document.createElement('details');raw.className='raw-toggle';raw.open=true;const summary=document.createElement('summary');summary.textContent='Raw event JSON';raw.append(summary,pre);details.append(title,sub,raw);const nodeMap=new Map();for(const node of(core.getGraph()?.nodes||[])){if(node?.id)nodeMap.set(node.id,node);for(const key of['viewer_member_ids','viewer_agent_member_ids'])for(const member of(node?.attributes?.[key]||[]))nodeMap.set(String(member),node)}const targets=document.createElement('div');targets.className='raw-target-actions';for(const entity of [event.source,event.target]){if(!entity?.id||!nodeMap.has(entity.id))continue;const node=nodeMap.get(entity.id);const button=document.createElement('button');button.type='button';button.textContent=`Inspect ${node.type||'node'}${node.name?` · ${node.name}`:''}`;button.addEventListener('click',()=>core.selectNode(node.id,{syncLog:false}));targets.appendChild(button)}if(targets.childElementCount)details.appendChild(targets)}
function selectRaw(entry,row){document.querySelectorAll('.raw-row.selected').forEach(el=>el.classList.remove('selected'));row.classList.add('selected');const edge=findGraphEdge(entry.event);if(edge)core.selectEdge(edge,{syncLog:false});showRaw(entry)}
function renderRaw(scrollLatest=false){rawRows.replaceChildren();activityCount.textContent=logMode==='raw'?`${rawEntries.length} raw event${rawEntries.length===1?'':'s'}`:`${core.getActivities().length} transition${core.getActivities().length===1?'':'s'}`;if(!rawEntries.length){const empty=document.createElement('div');empty.className='empty-activity';empty.textContent='Waiting for runtime or semantic activity…';rawRows.appendChild(empty);return}for(const entry of rawEntries){const row=document.createElement('div');row.className='raw-row';row.dataset.rawId=rawId(entry);const line=document.createElement('span');line.className='raw-line';line.textContent=String(entry.line??'—');const time=document.createElement('span');time.className='raw-time';time.textContent=rawTime(entry.event);const event=document.createElement('span');event.className='raw-event';event.textContent=rawEventType(entry.event);const relation=document.createElement('span');relation.className='raw-relation';relation.textContent=rawRelation(entry.event);const json=document.createElement('span');json.className='raw-json';json.textContent=rawSummary(entry.event);json.title=json.textContent;row.append(line,time,event,relation,json);row.onclick=()=>selectRaw(entry,row);rawRows.appendChild(row)}if(scrollLatest)rawRows.lastElementChild?.scrollIntoView({block:'nearest'})}
function setLogMode(mode){logMode=mode==='raw'?'raw':'structured';document.querySelectorAll('[data-log-mode]').forEach(button=>button.classList.toggle('active',button.dataset.logMode===logMode));structuredList.hidden=logMode==='raw';rawLog.hidden=logMode!=='raw';filterGroup.hidden=logMode==='raw';if(logMode==='raw')renderRaw(false);else activityCount.textContent=`${core.getActivities().length} transition${core.getActivities().length===1?'':'s'}`}
document.querySelectorAll('[data-log-mode]').forEach(button=>button.onclick=()=>setLogMode(button.dataset.logMode));
function onPayload(data){observeGifPayload(data);if(data.kind==='snapshot')setRawEntries(data.raw_events||[]);else if(data.kind==='delta'){const added=[];for(const update of data.updates||[])added.push(...(update.raw_events_added||[]));addRawEntries(added)}}
function timelineItems(){const activities=core.getActivities().filter(item=>item.edgeId||item.nodeId);return activities.length?activities:[]}
function revealNode(id){if(!id)return;document.querySelector(`.node[data-id="${CSS.escape(id)}"]`)?.classList.remove('replay-hidden')}
function revealEdge(id){if(!id)return;const edge=document.querySelector(`.edge[data-edge-id="${CSS.escape(id)}"]`);edge?.classList.remove('replay-hidden');document.querySelector(`.label[data-edge-id="${CSS.escape(id)}"]`)?.classList.remove('replay-hidden');if(edge){revealNode(edge.dataset.source);revealNode(edge.dataset.target)}}
function restoreReplayDom(){document.querySelectorAll('.replay-hidden,.replay-active').forEach(el=>el.classList.remove('replay-hidden','replay-active'))}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function replayRun(){if(replaying)return;const timeline=timelineItems();if(!timeline.length)return;replaying=true;replayButton.disabled=true;restoreReplayDom();document.querySelectorAll('.node,.edge,.label').forEach(el=>el.classList.add('replay-hidden'));core.setCameraMode('fit');const delay=Math.max(55,Math.min(180,7000/Math.max(1,timeline.length)));for(const item of timeline){document.querySelectorAll('.replay-active').forEach(el=>el.classList.remove('replay-active'));if(item.edgeId){revealEdge(item.edgeId);document.querySelector(`.edge[data-edge-id="${CSS.escape(item.edgeId)}"]`)?.classList.add('replay-active')}if(item.nodeId){revealNode(item.nodeId);document.querySelector(`.node[data-id="${CSS.escape(item.nodeId)}"]`)?.classList.add('replay-active')}core.markLatest(item.nodeId||null,item.edgeId||null);await sleep(delay)}await sleep(380);restoreReplayDom();const last=timeline[timeline.length-1];core.markLatest(last.nodeId||null,last.edgeId||null);replaying=false;replayButton.disabled=false}
""" + GIF_SCRIPT + r"""
async function prepareFinalView(){try{const response=await fetch('/final',{cache:'no-store'});if(!response.ok)throw new Error(String(response.status));finalHtmlCache=await response.text()}catch(_){finalHtmlCache=null}}
function openFinal(){if(!finalHtmlCache)return;document.open();document.write(finalHtmlCache);document.close()}
function onFinished(){if(finishedShown)return;finishedShown=true;finishedActions.hidden=false;prepareFinalView()}
replayButton.onclick=replayRun;gifButton.onclick=downloadGif;openFinalButton.onclick=openFinal;
window.__execweaveDashboard={onPayload,onFinished};
if(window.__execweaveStaticMode)onFinished();
})();
"""
