from __future__ import annotations

LIVE_STYLE = r""":root{color-scheme:dark;--bg:#0a0f16;--panel:#101722;--panel2:#151f2c;--panel3:#0d141e;--text:#edf2f7;--muted:#8fa0b5;--border:#263446;--border-strong:#34485e;--edge:#6f8298;--causal:#65c79b;--noncausal:#e5aa61;--inferred:#b18cff;--selected:#75b8ff;--latest:#77d7ff;--danger:#ff7b86;--node-agent:#203c55;--node-process:#253449;--node-file:#31402e;--node-network:#46362a;--node-tool:#3d3054;--node-model:#263c48;--node-other:#2b3542;--shadow:0 14px 40px rgba(0,0,0,.18)}
:root[data-theme="light"]{color-scheme:light;--bg:#eef3f8;--panel:#ffffff;--panel2:#f6f9fc;--panel3:#f9fbfd;--text:#172033;--muted:#66758a;--border:#d5dee8;--border-strong:#b9c7d7;--edge:#738195;--causal:#16855a;--noncausal:#b56a16;--inferred:#7b4dd8;--selected:#2563eb;--latest:#0f8fc5;--danger:#c2414f;--node-agent:#315b7a;--node-process:#46586d;--node-file:#4c6846;--node-network:#73553b;--node-tool:#65507f;--node-model:#456679;--node-other:#536173;--shadow:0 14px 35px rgba(30,41,59,.08)}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
button,input{font:inherit}button{color:inherit}button:focus-visible,input:focus-visible{outline:2px solid var(--selected);outline-offset:2px}
#app{display:grid;grid-template-columns:minmax(0,1fr) 340px;grid-template-rows:64px minmax(0,1fr) 230px;width:100%;height:100%;gap:0}
header{grid-column:1/3;display:flex;align-items:center;gap:12px;padding:0 16px;background:color-mix(in srgb,var(--panel) 95%,transparent);border-bottom:1px solid var(--border);box-shadow:0 1px 0 rgba(255,255,255,.02);z-index:10;min-width:0}
.brand{display:flex;align-items:center;gap:10px;min-width:max-content}.brand-mark{width:28px;height:28px;border-radius:8px;display:grid;place-items:center;background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--border-strong);font-weight:800;letter-spacing:-.06em}.brand-copy{display:flex;flex-direction:column;line-height:1.1}.brand-copy strong{font-size:14px}.brand-copy span{font-size:10px;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-top:3px}
#status{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--border);border-radius:999px;padding:4px 9px;color:var(--causal);background:var(--panel2);font-size:12px;font-weight:700;letter-spacing:.04em}.status-dot{width:7px;height:7px;border-radius:50%;background:currentColor;box-shadow:0 0 0 0 color-mix(in srgb,currentColor 40%,transparent);animation:statusPulse 1.8s ease-out infinite}#status.finished{color:var(--muted)}#status.reconnecting,#status.resyncing{color:var(--noncausal)}
@keyframes statusPulse{0%{box-shadow:0 0 0 0 color-mix(in srgb,currentColor 38%,transparent)}70%{box-shadow:0 0 0 7px transparent}100%{box-shadow:0 0 0 0 transparent}}
.header-metrics{display:flex;align-items:center;gap:8px;min-width:0}.metric-pill{border:1px solid var(--border);border-radius:999px;padding:4px 9px;background:var(--panel2);color:var(--muted);white-space:nowrap;font-size:12px}.metric-pill strong{color:var(--text);font-weight:650}#evidence.provisional{color:var(--noncausal);border-color:color-mix(in srgb,var(--noncausal) 50%,var(--border))}
.header-spacer{flex:1}.search-wrap{position:relative;width:min(390px,30vw);min-width:170px}.search-wrap::before{content:"⌕";position:absolute;left:10px;top:50%;transform:translateY(-52%);color:var(--muted);font-size:16px;pointer-events:none}header input{width:100%;padding:8px 10px 8px 30px;border:1px solid var(--border);border-radius:9px;background:var(--panel2);color:var(--text)}header input::placeholder{color:var(--muted)}
.icon-btn{height:34px;min-width:34px;padding:0 10px;border:1px solid var(--border);border-radius:8px;background:var(--panel2);cursor:pointer;transition:border-color .15s ease,background .15s ease}.icon-btn:hover{border-color:var(--border-strong);background:color-mix(in srgb,var(--panel2) 76%,var(--selected) 8%)}
#graph-panel{grid-column:1;grid-row:2;min-width:0;min-height:0;display:grid;grid-template-rows:46px minmax(0,1fr);border-right:1px solid var(--border);background:var(--panel3)}
.panel-bar{display:flex;align-items:center;gap:10px;padding:0 12px;border-bottom:1px solid var(--border);background:var(--panel);min-width:0}.panel-title{font-size:12px;font-weight:750;text-transform:uppercase;letter-spacing:.08em}.panel-subtitle{color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.panel-spacer{flex:1}
.segmented{display:flex;align-items:center;padding:2px;border:1px solid var(--border);border-radius:9px;background:var(--panel2);gap:2px}.segmented button{height:28px;padding:0 10px;border:0;border-radius:7px;background:transparent;color:var(--muted);cursor:pointer;font-size:12px}.segmented button:hover{color:var(--text)}.segmented button.active{background:var(--panel);color:var(--text);box-shadow:inset 0 0 0 1px var(--border-strong)}
.graph-actions{display:flex;align-items:center;gap:6px}.graph-actions button{height:30px;min-width:30px;padding:0 9px;border:1px solid var(--border);border-radius:8px;background:var(--panel2);cursor:pointer;color:var(--muted)}.graph-actions button:hover{color:var(--text);border-color:var(--border-strong)}
#wrap{position:relative;overflow:hidden;min-width:0;min-height:0;background-image:radial-gradient(circle at 1px 1px,color-mix(in srgb,var(--border) 52%,transparent) 1px,transparent 0);background-size:22px 22px}svg{width:100%;height:100%;display:block;cursor:grab;user-select:none;touch-action:none}svg.panning{cursor:grabbing}
#camera-hint{position:absolute;right:14px;bottom:14px;z-index:3;display:flex;align-items:center;gap:8px;padding:7px 9px;border:1px solid var(--border);border-radius:9px;background:color-mix(in srgb,var(--panel) 94%,transparent);box-shadow:var(--shadow);color:var(--muted);font-size:11px;backdrop-filter:blur(10px)}#camera-hint strong{color:var(--text)}
#jump-latest{position:absolute;right:14px;top:14px;z-index:3;padding:7px 10px;border:1px solid color-mix(in srgb,var(--latest) 45%,var(--border));border-radius:999px;background:color-mix(in srgb,var(--panel) 92%,transparent);color:var(--latest);cursor:pointer;box-shadow:var(--shadow)}#jump-latest[hidden]{display:none}
#protective{position:absolute;inset:18px;z-index:4;display:grid;place-items:center;padding:24px;text-align:center;border:1px solid var(--border);border-radius:14px;background:color-mix(in srgb,var(--panel) 96%,transparent);box-shadow:var(--shadow)}#protective[hidden]{display:none}#protective strong{display:block;margin-bottom:8px;font-size:18px}#protective p{max-width:680px;margin:6px auto;color:var(--muted)}
.node{cursor:pointer}.node rect{stroke:var(--border-strong);stroke-width:1.2;rx:10;ry:10;transition:opacity .15s ease,stroke .15s ease}.node text{fill:#f8fafc;pointer-events:none}.node .type{fill:#c6d2df;font-size:9px;text-transform:uppercase;letter-spacing:.05em}.node.dim{opacity:.1}.node.selected rect{stroke:var(--selected);stroke-width:2.4}.node.latest rect{stroke:var(--latest);animation:latestNode 1.55s ease-out infinite}
@keyframes latestNode{0%{stroke-width:2.2;stroke-opacity:1}55%{stroke-width:6;stroke-opacity:.28}100%{stroke-width:2.2;stroke-opacity:1}}
.edge{fill:none;stroke:var(--edge);stroke-width:1.4;opacity:.72;marker-end:url(#arrow)}.edge.causal{stroke:var(--causal)}.edge.noncausal{stroke:var(--noncausal);stroke-dasharray:6 5}.edge.inferred{stroke:var(--inferred);stroke-dasharray:4 5}.edge.dim{opacity:.05}.edge.selected{stroke-width:2.5;opacity:1}.edge.latest-edge{stroke:var(--latest);stroke-width:2;stroke-dasharray:9 6;opacity:1;animation:latestEdge .9s linear infinite}.edge-hit{fill:none;stroke:transparent;stroke-width:12;cursor:pointer}.label{fill:var(--muted);font-size:8.5px;pointer-events:none}.label.selected{fill:var(--selected)}
@keyframes latestEdge{to{stroke-dashoffset:-30}}
#inspector{grid-column:2;grid-row:2;min-width:0;min-height:0;overflow:auto;background:var(--panel);padding:14px}.inspector-section+.inspector-section{margin-top:18px;padding-top:16px;border-top:1px solid var(--border)}.eyebrow{font-size:10px;letter-spacing:.09em;text-transform:uppercase;color:var(--muted);font-weight:750}.current-title{font-size:16px;font-weight:750;margin-top:6px;overflow-wrap:anywhere}.current-sub{color:var(--muted);font-size:12px;margin-top:4px;overflow-wrap:anywhere}.kv{display:grid;grid-template-columns:92px minmax(0,1fr);gap:7px 10px;margin-top:12px;font-size:12px}.kv dt{color:var(--muted)}.kv dd{margin:0;overflow-wrap:anywhere}.badge{display:inline-flex;align-items:center;border:1px solid var(--border);border-radius:999px;padding:2px 7px;background:var(--panel2);font-size:10px;color:var(--muted)}.badge.direct{color:var(--causal);border-color:color-mix(in srgb,var(--causal) 45%,var(--border))}.badge.inferred{color:var(--inferred);border-color:color-mix(in srgb,var(--inferred) 45%,var(--border))}
#details-empty{color:var(--muted);font-size:12px;margin-top:8px}.raw-toggle{margin-top:12px}.raw-toggle summary{cursor:pointer;color:var(--muted);font-size:11px}.raw-toggle pre{white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;background:var(--panel3);border:1px solid var(--border);border-radius:9px;padding:10px;margin:8px 0 0}.raw-target-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.raw-target-actions button{padding:4px 8px;font-size:11px}
#activity-panel{grid-column:1/3;grid-row:3;min-width:0;min-height:0;display:grid;grid-template-rows:44px minmax(0,1fr);background:var(--panel);border-top:1px solid var(--border)}.activity-toolbar{display:flex;align-items:center;gap:10px;padding:0 12px;border-bottom:1px solid var(--border)}.activity-toolbar .count{color:var(--muted);font-size:11px}.filter-group{display:flex;gap:5px;margin-left:auto}.filter-group button{height:27px;padding:0 9px;border:1px solid transparent;border-radius:7px;background:transparent;color:var(--muted);font-size:11px;cursor:pointer}.filter-group button.active{border-color:var(--border);background:var(--panel2);color:var(--text)}
#activity-list{overflow:auto;min-height:0}.activity-head,.activity-row{display:grid;grid-template-columns:92px 96px 170px minmax(220px,1fr) 130px;align-items:center;gap:10px;padding:0 12px}.activity-head{height:28px;position:sticky;top:0;z-index:2;background:var(--panel);border-bottom:1px solid var(--border);color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.activity-row{min-height:38px;border-bottom:1px solid color-mix(in srgb,var(--border) 72%,transparent);font-size:11px;cursor:pointer}.activity-row:hover{background:var(--panel2)}.activity-row.selected{background:color-mix(in srgb,var(--selected) 10%,var(--panel));box-shadow:inset 2px 0 0 var(--selected)}.activity-row.latest{background:color-mix(in srgb,var(--latest) 8%,var(--panel))}.activity-time{color:var(--muted);font-variant-numeric:tabular-nums}.activity-kind{font-size:9px;text-transform:uppercase;letter-spacing:.06em}.activity-relation{font-weight:700}.activity-detail{color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.activity-evidence{color:var(--muted)}.empty-activity{padding:22px;color:var(--muted);text-align:center;font-size:12px}
@media(max-width:980px){#app{grid-template-columns:minmax(0,1fr) 290px}.header-metrics .optional{display:none}.search-wrap{width:min(300px,28vw)}.activity-head,.activity-row{grid-template-columns:82px 82px 130px minmax(180px,1fr) 100px}}
@media(max-width:760px){html,body{overflow:auto}#app{height:auto;min-height:100%;grid-template-columns:1fr;grid-template-rows:auto 520px auto 260px}header{grid-column:1;flex-wrap:wrap;height:auto;padding:10px 12px}.header-spacer{display:none}.search-wrap{order:5;width:100%}#graph-panel{grid-column:1;grid-row:2;border-right:0}.panel-subtitle{display:none}#inspector{grid-column:1;grid-row:3;border-top:1px solid var(--border);max-height:340px}#activity-panel{grid-column:1;grid-row:4}.activity-head,.activity-row{grid-template-columns:80px 82px minmax(160px,1fr);}.activity-head>*:nth-child(4),.activity-head>*:nth-child(5),.activity-row>*:nth-child(4),.activity-row>*:nth-child(5){display:none}}
@media(prefers-reduced-motion:reduce){.status-dot,.node.latest rect,.edge.latest-edge{animation:none}.node.latest rect{stroke-width:3}.edge.latest-edge{stroke-dasharray:none}}"""
