from __future__ import annotations

LIVE_SCRIPT_A = r"""(()=>{
const MAX_NODES=1500,MAX_EDGES=4000,MAX_DOM_ELEMENTS=5000,MAX_ACTIVITY=240,THEME_KEY='execweave-theme',VIEWER_LIMITS=window.__execweaveViewerLimits||{};
const ACTIVE_MAX_NODES=Number(VIEWER_LIMITS.max_nodes)||MAX_NODES,ACTIVE_MAX_EDGES=Number(VIEWER_LIMITS.max_edges)||MAX_EDGES,ACTIVE_MAX_DOM_ELEMENTS=Number(VIEWER_LIMITS.max_dom_elements)||MAX_DOM_ELEMENTS;
const svg=document.getElementById('svg'),viewport=document.getElementById('viewport'),edgeLayer=document.getElementById('edges'),labelLayer=document.getElementById('labels'),nodeLayer=document.getElementById('nodes'),details=document.getElementById('details'),detailsEmpty=document.getElementById('details-empty'),search=document.getElementById('search'),stats=document.getElementById('stats'),evidence=document.getElementById('evidence'),status=document.getElementById('status'),statusLabel=document.getElementById('status-label'),protective=document.getElementById('protective'),protectiveSummary=document.getElementById('protective-summary'),themeToggle=document.getElementById('theme-toggle'),cameraLabel=document.getElementById('camera-label'),jumpLatest=document.getElementById('jump-latest'),currentTitle=document.getElementById('current-title'),currentSub=document.getElementById('current-sub'),currentKv=document.getElementById('current-kv'),activityRows=document.getElementById('activity-rows'),activityCount=document.getElementById('activity-count'),activityList=document.getElementById('activity-list');
let graph={nodes:[],edges:[]},nodeById=new Map(),edgeById=new Map(),positions=new Map(),incomingByNode=new Map(),outgoingByNode=new Map(),layerRows=new Map(),nodeElements=new Map(),edgeElements=new Map(),transform={x:35,y:35,scale:1},pan=null,liveSequence=-1,hasFitted=false,protectedMode=false,cameraMode='manual',latestNodeId=null,latestEdgeId=null,selectedNodeId=null,selectedEdgeId=null,activities=[],activityFilter='all',cameraTimer=null,animationFrame=null,activitySerial=0;
function applyTheme(theme,persist=false){const next=theme==='light'?'light':'dark';document.documentElement.dataset.theme=next;const light=next==='light';themeToggle.textContent=light?'Dark':'Light';themeToggle.setAttribute('aria-label',light?'Switch to dark theme':'Switch to light theme');themeToggle.title=light?'Switch to dark theme':'Switch to light theme';if(persist){try{localStorage.setItem(THEME_KEY,next)}catch(_){}}}
function initialTheme(){try{return localStorage.getItem(THEME_KEY)==='light'?'light':'dark'}catch(_){return'dark'}}
function edgeId(e){return e.id||`${e.source}:${e.relation}:${e.target}`}
function shortText(value,max=32){const text=String(value??'');return text.length>max?text.slice(0,max-1)+'…':text}
function short(node){return shortText(node?.name||node?.id||node?.type||'node',28)}
function nodeColor(type){const value=String(type||'').toLowerCase();if(value.includes('session')||value.includes('agent'))return'var(--node-agent)';if(value.includes('process')||value.includes('shell'))return'var(--node-process)';if(value.includes('file')||value.includes('path'))return'var(--node-file)';if(value.includes('network')||value.includes('socket')||value.includes('endpoint')||value.includes('host'))return'var(--node-network)';if(value.includes('tool'))return'var(--node-tool)';if(value.includes('model')||value.includes('inference')||value.includes('llm'))return'var(--node-model)';return'var(--node-other)'}
function nodeCategory(node){const value=String(node?.type||'').toLowerCase();if(value.includes('process')||value.includes('shell'))return'process';if(value.includes('file')||value.includes('path'))return'file';if(value.includes('network')||value.includes('socket')||value.includes('endpoint')||value.includes('host'))return'network';if(value.includes('tool'))return'tool';if(value.includes('model')||value.includes('inference')||value.includes('llm'))return'model';return'other'}
function graphCounts(data){const nodes=Number(data.node_count)||((data.nodes||[]).length),edges=Number(data.edge_count)||((data.edges||[]).length);return{nodes,edges,estimated:nodes*4+edges*3}}
function withinRenderBudget(data){const counts=graphCounts(data);return counts.nodes<=ACTIVE_MAX_NODES&&counts.edges<=ACTIVE_MAX_EDGES&&counts.estimated<=ACTIVE_MAX_DOM_ELEMENTS}
function updateStats(data){stats.innerHTML=`<strong>${Number(data.node_count)||0}</strong> nodes · <strong>${Number(data.edge_count)||0}</strong> edges · <strong>${Number(data.event_count)||0}</strong> events`}
function updateEvidence(data){const counts=data.live_evidence_counts||{},runtime=Number(counts.os_runtime)||0,specialized=Number(counts.specialized)||0,provisional=!!data.live_specialized_provisional;evidence.innerHTML=`OS <strong>${runtime}</strong> · specialized <strong>${specialized}</strong>${provisional?' · provisional':''}`;evidence.classList.toggle('provisional',provisional);evidence.title=provisional?'Specialized evidence is provisional until the canonical final merge.':'Observed evidence counts for this live session.'}
function setStatus(label,kind=''){statusLabel.textContent=label;status.className=kind}
function enterProtectiveMode(data){const counts=graphCounts(data);edgeLayer.replaceChildren();labelLayer.replaceChildren();nodeLayer.replaceChildren();positions=new Map();nodeElements=new Map();edgeElements=new Map();svg.style.display='none';protective.hidden=false;protectiveSummary.textContent=`${counts.nodes} nodes · ${counts.edges} edges · about ${counts.estimated} SVG elements exceeds the live safety budget.`;setStatus('PROTECTED','reconnecting');protectedMode=true}
function leaveProtectiveMode(){protective.hidden=true;svg.style.display='block';protectedMode=false}
function registerEdgeAdjacency(e){const id=edgeId(e);if(!incomingByNode.has(e.target))incomingByNode.set(e.target,new Set());if(!outgoingByNode.has(e.source))outgoingByNode.set(e.source,new Set());incomingByNode.get(e.target).add(id);outgoingByNode.get(e.source).add(id)}
function rebuildAdjacency(){incomingByNode=new Map();outgoingByNode=new Map();for(const e of edgeById.values())registerEdgeAdjacency(e)}
function fullLayout(){positions=new Map();const ids=[...nodeById.keys()],incomingCount=new Map(ids.map(id=>[id,0])),outgoing=new Map(ids.map(id=>[id,[]]));for(const e of edgeById.values()){if(!nodeById.has(e.source)||!nodeById.has(e.target))continue;incomingCount.set(e.target,(incomingCount.get(e.target)||0)+1);outgoing.get(e.source).push(e.target)}let roots=ids.filter(id=>(incomingCount.get(id)||0)===0);if(!roots.length&&ids.length)roots=[ids[0]];const depth=new Map(),queue=roots.map(id=>[id,0]);for(let i=0;i<queue.length;i++){const [id,d]=queue[i];if(depth.has(id))continue;depth.set(id,d);for(const next of outgoing.get(id)||[])queue.push([next,d+1])}let maxDepth=0;depth.forEach(value=>{if(value>maxDepth)maxDepth=value});for(const id of ids)if(!depth.has(id))depth.set(id,maxDepth+1);const layers=new Map();for(const id of ids){const d=depth.get(id);if(!layers.has(d))layers.set(d,[]);layers.get(d).push(id)}layerRows=new Map();for(const [d,list] of layers){list.sort((a,b)=>String(nodeById.get(a)?.type).localeCompare(String(nodeById.get(b)?.type))||a.localeCompare(b));list.forEach((id,i)=>positions.set(id,{x:d*235,y:i*76}));layerRows.set(d,list.length)}}
function reservePosition(depth){const row=layerRows.get(depth)||0;layerRows.set(depth,row+1);return{x:depth*235,y:row*76}}
function nodeDepth(id){const p=positions.get(id);return p?Math.max(0,Math.round(p.x/235)):null}
function placeAddedNodes(ids){const pending=new Set(ids.filter(id=>nodeById.has(id)&&!positions.has(id)));while(pending.size){let progress=false;for(const id of [...pending]){const incoming=[...(incomingByNode.get(id)||[])].map(edgeIdValue=>edgeById.get(edgeIdValue)).filter(Boolean);const parentDepths=incoming.map(e=>nodeDepth(e.source)).filter(d=>d!==null);if(parentDepths.length){positions.set(id,reservePosition(Math.max(...parentDepths)+1));pending.delete(id);progress=true;continue}const outgoing=[...(outgoingByNode.get(id)||[])].map(edgeIdValue=>edgeById.get(edgeIdValue)).filter(Boolean);const targetDepths=outgoing.map(e=>nodeDepth(e.target)).filter(d=>d!==null);if(targetDepths.length){positions.set(id,reservePosition(Math.max(0,Math.min(...targetDepths)-1)));pending.delete(id);progress=true}}if(progress)continue;const id=pending.values().next().value;positions.set(id,reservePosition(0));pending.delete(id)}}
function anchor(id,right){const p=positions.get(id)||{x:0,y:0};return{x:p.x+(right?160:0),y:p.y+25}}
function curve(e){const a=anchor(e.source,true),b=anchor(e.target,false),bend=Math.max(38,Math.abs(b.x-a.x)*.42);return `M ${a.x} ${a.y} C ${a.x+bend} ${a.y}, ${b.x-bend} ${b.y}, ${b.x} ${b.y}`}
function currentEdge(id,fallback){return edgeById.get(id)||fallback}
function currentNode(id,fallback){return nodeById.get(id)||fallback}
function evidenceLabel(value){if(value?.inferred===true)return'Inferred';if(value?.causal===true)return'Direct / causal';if(value?.causal===false)return'Observed / non-causal';return'Observed'}
function evidenceClass(value){return value?.inferred===true?'inferred':value?.causal===true?'direct':''}
function prettyTime(value){if(!value)return'—';const date=new Date(value);if(Number.isNaN(date.getTime()))return shortText(value,18);return date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3})}
function entityLabel(id){const node=nodeById.get(id);return node?.name||node?.id||id||'unknown'}
function renderKv(target,entries){target.replaceChildren();for(const [key,value] of entries){if(value===null||value===undefined||value==='')continue;const dt=document.createElement('dt');dt.textContent=key;const dd=document.createElement('dd');if(key==='Evidence'){const badge=document.createElement('span');badge.className='badge '+evidenceClass(value.raw||{});badge.textContent=value.label||String(value);dd.appendChild(badge)}else dd.textContent=String(value);target.append(dt,dd)}}
function show(value,kind='Selection'){detailsEmpty.hidden=true;details.innerHTML='';const title=document.createElement('div');title.className='current-title';title.textContent=kind==='Node'?(value.name||value.id||'Node'):kind==='Edge'?(value.relation||value.id||'Edge'):kind;const sub=document.createElement('div');sub.className='current-sub';sub.textContent=kind==='Node'?(value.type||'unknown'):kind==='Edge'?`${entityLabel(value.source)} → ${entityLabel(value.target)}`:'';const dl=document.createElement('dl');dl.className='kv';const entries=kind==='Node'?[['Type',value.type],['Events',value.event_count],['First seen',prettyTime(value.first_seen)],['Last seen',prettyTime(value.last_seen)]]:[['Count',value.count],['Last seen',prettyTime(value.last_seen)],['Sequence',value.last_sequence],['Evidence',{label:evidenceLabel(value),raw:value}]];renderKv(dl,entries);const raw=document.createElement('details');raw.className='raw-toggle';const summary=document.createElement('summary');summary.textContent='Raw metadata';const pre=document.createElement('pre');pre.textContent=JSON.stringify(value,null,2);raw.append(summary,pre);details.append(title,sub,dl,raw)}
function clearSelection(){if(selectedNodeId&&nodeElements.has(selectedNodeId))nodeElements.get(selectedNodeId).classList.remove('selected');if(selectedEdgeId&&edgeElements.has(selectedEdgeId)){const els=edgeElements.get(selectedEdgeId);els.visible.classList.remove('selected');els.label.classList.remove('selected')}selectedNodeId=null;selectedEdgeId=null;document.querySelectorAll('.activity-row.selected').forEach(row=>row.classList.remove('selected'))}
function selectNode(id,{syncLog=true}={}){const node=nodeById.get(id);if(!node)return;clearSelection();selectedNodeId=id;nodeElements.get(id)?.classList.add('selected');show(node,'Node');window.__execweaveFocusConversationAgent?.(node);if(syncLog){const activity=[...activities].reverse().find(item=>item.nodeId===id);if(activity)selectActivityRow(activity.id,false)}}
function selectEdge(id,{syncLog=true}={}){const edge=edgeById.get(id);if(!edge)return;clearSelection();window.__execweaveClearConversationFocus?.();selectedEdgeId=id;const els=edgeElements.get(id);if(els){els.visible.classList.add('selected');els.label.classList.add('selected')}show(edge,'Edge');if(syncLog){const activity=[...activities].reverse().find(item=>item.edgeId===id);if(activity)selectActivityRow(activity.id,false)}}
function createNodeElement(n){if(nodeElements.has(n.id))return updateNodeElement(n);const p=positions.get(n.id);if(!p)return;const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.classList.add('node');group.dataset.id=n.id;group.setAttribute('transform',`translate(${p.x} ${p.y})`);const rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('width',160);rect.setAttribute('height',50);group.appendChild(rect);const type=document.createElementNS('http://www.w3.org/2000/svg','text');type.setAttribute('x',10);type.setAttribute('y',15);type.classList.add('type');group.appendChild(type);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',10);label.setAttribute('y',34);label.classList.add('name-label');group.appendChild(label);group.onclick=ev=>{ev.stopPropagation();selectNode(n.id)};nodeLayer.appendChild(group);nodeElements.set(n.id,group);updateNodeElement(n)}
function updateNodeElement(n){const group=nodeElements.get(n.id);if(!group)return;group.dataset.search=`${n.id} ${n.name||''} ${n.type||''}`.toLowerCase();const rect=group.querySelector('rect');if(rect)rect.setAttribute('fill',nodeColor(n.type));const type=group.querySelector('.type');if(type)type.textContent=n.type||'unknown';const label=group.querySelector('.name-label');if(label)label.textContent=short(n);group.classList.toggle('latest',n.id===latestNodeId);group.classList.toggle('selected',n.id===selectedNodeId)}
function createEdgeElement(e){const id=edgeId(e);if(edgeElements.has(id))return updateEdgeElement(e);if(!positions.has(e.source)||!positions.has(e.target))return;const visible=document.createElementNS('http://www.w3.org/2000/svg','path');visible.classList.add('edge');visible.dataset.edgeId=id;edgeLayer.appendChild(visible);const hit=document.createElementNS('http://www.w3.org/2000/svg','path');hit.classList.add('edge-hit');hit.dataset.edgeId=id;hit.onclick=ev=>{ev.stopPropagation();selectEdge(id)};edgeLayer.appendChild(hit);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('text-anchor','middle');label.classList.add('label');label.dataset.edgeId=id;labelLayer.appendChild(label);edgeElements.set(id,{visible,hit,label});updateEdgeElement(e)}
function updateEdgeElement(e){const id=edgeId(e),els=edgeElements.get(id);if(!els)return;const d=curve(e);els.visible.setAttribute('d',d);els.hit.setAttribute('d',d);els.visible.classList.toggle('causal',e.causal===true);els.visible.classList.toggle('noncausal',e.causal===false);els.visible.classList.toggle('inferred',e.inferred===true);els.visible.classList.toggle('latest-edge',id===latestEdgeId);els.visible.classList.toggle('selected',id===selectedEdgeId);els.label.classList.toggle('selected',id===selectedEdgeId);els.visible.dataset.source=e.source;els.visible.dataset.target=e.target;els.visible.dataset.relation=String(e.relation||'').toLowerCase();const a=anchor(e.source,true),b=anchor(e.target,false);els.label.setAttribute('x',(a.x+b.x)/2);els.label.setAttribute('y',(a.y+b.y)/2-6);els.label.textContent=e.count>1?`${e.relation} ×${e.count}`:e.relation}
"""
