from __future__ import annotations

LIVE_EXTRA_STYLE = r"""
.finished-actions{display:flex;align-items:center;gap:6px}.finished-actions[hidden]{display:none}.finished-actions button,.log-tabs button{height:28px;padding:0 9px;border:1px solid var(--border);border-radius:7px;background:var(--panel2);color:var(--muted);font-size:11px;cursor:pointer}.finished-actions button:hover,.log-tabs button:hover{color:var(--text);border-color:var(--border-strong)}#download-gif{color:var(--latest);border-color:color-mix(in srgb,var(--latest) 40%,var(--border))}#download-gif:disabled{opacity:.55;cursor:progress}
.log-tabs{display:flex;gap:4px;margin-left:auto}.log-tabs button.active{background:var(--panel);color:var(--text);box-shadow:inset 0 0 0 1px var(--border-strong)}.filter-group{margin-left:0}
#raw-log{overflow:auto;min-height:0}#raw-log[hidden]{display:none}.raw-head,.raw-row{display:grid;grid-template-columns:64px 92px 190px 170px minmax(300px,1fr);align-items:center;gap:10px;padding:0 12px}.raw-head{height:28px;position:sticky;top:0;z-index:2;background:var(--panel);border-bottom:1px solid var(--border);color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.raw-row{min-height:38px;border-bottom:1px solid color-mix(in srgb,var(--border) 72%,transparent);font:11px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;cursor:pointer}.raw-row:hover{background:var(--panel2)}.raw-row.selected{background:color-mix(in srgb,var(--selected) 10%,var(--panel));box-shadow:inset 2px 0 0 var(--selected)}.raw-line,.raw-time{color:var(--muted);font-variant-numeric:tabular-nums}.raw-event{color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.raw-relation{font-weight:700}.raw-json{color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.replay-hidden{opacity:0!important;pointer-events:none}.replay-active rect{stroke:var(--latest)!important;stroke-width:3!important}.edge.replay-active{stroke:var(--latest)!important;stroke-width:2.4!important;opacity:1!important}
@media(max-width:1100px){.finished-actions #open-final{display:none}.raw-head,.raw-row{grid-template-columns:54px 82px 150px 130px minmax(260px,1fr)}}
@media(max-width:760px){.finished-actions{order:4;margin-left:auto}.log-tabs{margin-left:auto}.filter-group{display:none}.raw-head,.raw-row{grid-template-columns:48px 78px minmax(220px,1fr)}.raw-head>*:nth-child(4),.raw-head>*:nth-child(5),.raw-row>*:nth-child(4),.raw-row>*:nth-child(5){display:none}}
"""
