from __future__ import annotations

LIVE_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ExecWeave Live</title>
<style>
:root{color-scheme:dark;--bg:#0b0f14;--panel:#111821;--panel2:#18222e;--text:#e8edf3;--muted:#8ea0b5;--border:#2a3949;--edge:#72869c;--causal:#70d6a6;--noncausal:#f2b76d;--selected:#73b7ff}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font:14px/1.4 system-ui,sans-serif}
#app{display:grid;grid-template-columns:minmax(0,1fr) 320px;grid-template-rows:54px minmax(0,1fr);width:100%;height:100%}
header{grid-column:1/3;display:flex;align-items:center;gap:12px;padding:0 14px;background:var(--panel);border-bottom:1px solid var(--border)}
#status{border:1px solid var(--border);border-radius:999px;padding:3px 8px;color:var(--causal)}#stats{color:var(--muted);white-space:nowrap}
header input{margin-left:auto;width:min(420px,36vw);padding:7px 9px;border:1px solid var(--border);border-radius:7px;background:var(--panel2);color:var(--text)}
#wrap{position:relative;overflow:hidden}svg{width:100%;height:100%;display:block;cursor:grab;user-select:none}svg.panning{cursor:grabbing}
#protective{position:absolute;inset:18px;z-index:4;display:grid;place-items:center;padding:24px;text-align:center;border:1px solid var(--border);border-radius:12px;background:rgba(17,24,33,.96)}#protective[hidden]{display:none}#protective strong{display:block;margin-bottom:8px;font-size:20px}#protective p{max-width:680px;margin:6px auto;color:var(--muted)}
aside{overflow:auto;border-left:1px solid var(--border);background:var(--panel);padding:13px}aside pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.45 ui-monospace,monospace}
.controls{position:absolute;left:10px;top:10px;z-index:3}.controls button{padding:6px 9px;border:1px solid var(--border);border-radius:7px;background:var(--panel);color:var(--text);cursor:pointer}
.node rect{stroke:var(--border);stroke-width:1.1;rx:8;ry:8}.node text{fill:var(--text);pointer-events:none}.node .type{fill:var(--muted);font-size:9px}.node.dim{opacity:.12}
.edge{fill:none;stroke:var(--edge);stroke-width:1.3;opacity:.72;marker-end:url(#arrow)}.edge.causal{stroke:var(--causal)}.edge.noncausal{stroke:var(--noncausal);stroke-dasharray:6 5}.edge.dim{opacity:.06}.edge-hit{fill:none;stroke:transparent;stroke-width:10;cursor:pointer}.label{fill:var(--muted);font-size:8.5px;pointer-events:none}
@media(max-width:820px){#app{grid-template-columns:1fr;grid-template-rows:54px minmax(0,1fr) 190px}header{grid-column:1}aside{border-left:0;border-top:1px solid var(--border)}}
</style>
</head>
<body>
<div id="app">
<header><strong>ExecWeave Live</strong><span id="status">LIVE</span><span id="stats">Waiting for events…</span><input id="search" placeholder="Search node id, name, type…"></header>
<div id="wrap"><div class="controls"><button id="fit">Fit</button></div><div id="protective" hidden><div><strong>LARGE GRAPH PROTECTIVE MODE</strong><p id="protective-summary"></p><p>Live SVG rendering has stopped to protect browser memory. Collection continues and no evidence is deleted or reclassified.</p></div></div><svg id="svg"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="context-stroke"></path></marker></defs><g id="viewport"><g id="edges"></g><g id="labels"></g><g id="nodes"></g></g></svg></div>
<aside><strong>Selection</strong><div id="details" style="color:var(--muted);margin-top:10px">Click a node or edge.</div></aside>
</div>
<script>
(()=>{
const MAX_NODES=1500,MAX_EDGES=4000,MAX_DOM_ELEMENTS=5000;
const svg=document.getElementById('svg'),viewport=document.getElementById('viewport'),edgeLayer=document.getElementById('edges'),labelLayer=document.getElementById('labels'),nodeLayer=document.getElementById('nodes'),details=document.getElementById('details'),search=document.getElementById('search'),stats=document.getElementById('stats'),status=document.getElementById('status'),protective=document.getElementById('protective'),protectiveSummary=document.getElementById('protective-summary');
let graph={nodes:[],edges:[]},nodeById=new Map(),edgeById=new Map(),positions=new Map(),incomingByNode=new Map(),outgoingByNode=new Map(),layerRows=new Map(),nodeElements=new Map(),edgeElements=new Map(),transform={x:35,y:35,scale:1},pan=null,liveSequence=-1,hasFitted=false,protectedMode=false,lastSignature='';
function edgeId(e){return e.id||`${e.source}:${e.relation}:${e.target}`}
function color(type){let h=0;for(const c of String(type||'unknown'))h=((h<<5)-h+c.charCodeAt(0))|0;return `hsl(${Math.abs(h)%360} 38% 27%)`}
function short(node){const value=node.name||node.id||node.type||'node';return value.length>28?value.slice(0,25)+'…':value}
function graphCounts(data){const nodes=Number(data.node_count)||((data.nodes||[]).length),edges=Number(data.edge_count)||((data.edges||[]).length);return{nodes,edges,estimated:nodes*4+edges*3}}
function withinRenderBudget(data){const counts=graphCounts(data);return counts.nodes<=MAX_NODES&&counts.edges<=MAX_EDGES&&counts.estimated<=MAX_DOM_ELEMENTS}
function updateStats(data){stats.textContent=`${Number(data.node_count)||0} nodes · ${Number(data.edge_count)||0} edges · ${Number(data.event_count)||0} events`}
function enterProtectiveMode(data){const counts=graphCounts(data);edgeLayer.replaceChildren();labelLayer.replaceChildren();nodeLayer.replaceChildren();positions=new Map();nodeElements=new Map();edgeElements=new Map();svg.style.display='none';protective.hidden=false;protectiveSummary.textContent=`${counts.nodes} nodes · ${counts.edges} edges · about ${counts.estimated} SVG elements exceeds the live safety budget.`;status.textContent='PROTECTED';protectedMode=true}
function leaveProtectiveMode(){protective.hidden=true;svg.style.display='block';protectedMode=false}
function registerEdgeAdjacency(e){const id=edgeId(e);if(!incomingByNode.has(e.target))incomingByNode.set(e.target,new Set());if(!outgoingByNode.has(e.source))outgoingByNode.set(e.source,new Set());incomingByNode.get(e.target).add(id);outgoingByNode.get(e.source).add(id)}
function rebuildAdjacency(){incomingByNode=new Map();outgoingByNode=new Map();for(const e of edgeById.values())registerEdgeAdjacency(e)}
function fullLayout(){positions=new Map();const ids=[...nodeById.keys()],incomingCount=new Map(ids.map(id=>[id,0])),outgoing=new Map(ids.map(id=>[id,[]]));for(const e of edgeById.values()){if(!nodeById.has(e.source)||!nodeById.has(e.target))continue;incomingCount.set(e.target,(incomingCount.get(e.target)||0)+1);outgoing.get(e.source).push(e.target)}let roots=ids.filter(id=>(incomingCount.get(id)||0)===0);if(!roots.length&&ids.length)roots=[ids[0]];const depth=new Map(),queue=roots.map(id=>[id,0]);for(let i=0;i<queue.length;i++){const [id,d]=queue[i];if(depth.has(id))continue;depth.set(id,d);for(const next of outgoing.get(id)||[])queue.push([next,d+1])}let maxDepth=0;depth.forEach(value=>{if(value>maxDepth)maxDepth=value});for(const id of ids)if(!depth.has(id))depth.set(id,maxDepth+1);const layers=new Map();for(const id of ids){const d=depth.get(id);if(!layers.has(d))layers.set(d,[]);layers.get(d).push(id)}layerRows=new Map();for(const [d,list] of layers){list.sort((a,b)=>String(nodeById.get(a)?.type).localeCompare(String(nodeById.get(b)?.type))||a.localeCompare(b));list.forEach((id,i)=>positions.set(id,{x:d*235,y:i*76}));layerRows.set(d,list.length)}}
function reservePosition(depth){const row=layerRows.get(depth)||0;layerRows.set(depth,row+1);return{x:depth*235,y:row*76}}
function nodeDepth(id){const p=positions.get(id);return p?Math.max(0,Math.round(p.x/235)):null}
function placeAddedNodes(ids){const pending=new Set(ids.filter(id=>nodeById.has(id)&&!positions.has(id)));while(pending.size){let progress=false;for(const id of [...pending]){const incoming=[...(incomingByNode.get(id)||[])].map(edgeIdValue=>edgeById.get(edgeIdValue)).filter(Boolean);const parentDepths=incoming.map(e=>nodeDepth(e.source)).filter(d=>d!==null);if(parentDepths.length){positions.set(id,reservePosition(Math.max(...parentDepths)+1));pending.delete(id);progress=true;continue}const outgoing=[...(outgoingByNode.get(id)||[])].map(edgeIdValue=>edgeById.get(edgeIdValue)).filter(Boolean);const targetDepths=outgoing.map(e=>nodeDepth(e.target)).filter(d=>d!==null);if(targetDepths.length){positions.set(id,reservePosition(Math.max(0,Math.min(...targetDepths)-1)));pending.delete(id);progress=true}}if(progress)continue;const id=pending.values().next().value;positions.set(id,reservePosition(0));pending.delete(id)}}
function anchor(id,right){const p=positions.get(id)||{x:0,y:0};return{x:p.x+(right?160:0),y:p.y+25}}
function curve(e){const a=anchor(e.source,true),b=anchor(e.target,false),bend=Math.max(38,Math.abs(b.x-a.x)*.42);return `M ${a.x} ${a.y} C ${a.x+bend} ${a.y}, ${b.x-bend} ${b.y}, ${b.x} ${b.y}`}
function currentEdge(id,fallback){return edgeById.get(id)||fallback}
function currentNode(id,fallback){return nodeById.get(id)||fallback}
function show(value){details.innerHTML='';const pre=document.createElement('pre');pre.textContent=JSON.stringify(value,null,2);details.appendChild(pre)}
function createNodeElement(n){if(nodeElements.has(n.id))return updateNodeElement(n);const p=positions.get(n.id);if(!p)return;const group=document.createElementNS('http://www.w3.org/2000/svg','g');group.classList.add('node');group.dataset.id=n.id;group.setAttribute('transform',`translate(${p.x} ${p.y})`);const rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('width',160);rect.setAttribute('height',50);group.appendChild(rect);const type=document.createElementNS('http://www.w3.org/2000/svg','text');type.setAttribute('x',10);type.setAttribute('y',15);type.classList.add('type');group.appendChild(type);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('x',10);label.setAttribute('y',34);label.classList.add('name-label');group.appendChild(label);group.onclick=ev=>{ev.stopPropagation();show(currentNode(n.id,n))};nodeLayer.appendChild(group);nodeElements.set(n.id,group);updateNodeElement(n)}
function updateNodeElement(n){const group=nodeElements.get(n.id);if(!group)return;group.dataset.search=`${n.id} ${n.name||''} ${n.type||''}`.toLowerCase();const rect=group.querySelector('rect');if(rect)rect.setAttribute('fill',color(n.type));const type=group.querySelector('.type');if(type)type.textContent=n.type||'unknown';const label=group.querySelector('.name-label');if(label)label.textContent=short(n)}
function createEdgeElement(e){const id=edgeId(e);if(edgeElements.has(id))return updateEdgeElement(e);if(!positions.has(e.source)||!positions.has(e.target))return;const visible=document.createElementNS('http://www.w3.org/2000/svg','path');visible.classList.add('edge');visible.dataset.edgeId=id;edgeLayer.appendChild(visible);const hit=document.createElementNS('http://www.w3.org/2000/svg','path');hit.classList.add('edge-hit');hit.dataset.edgeId=id;hit.onclick=ev=>{ev.stopPropagation();show(currentEdge(id,e))};edgeLayer.appendChild(hit);const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.setAttribute('text-anchor','middle');label.classList.add('label');label.dataset.edgeId=id;labelLayer.appendChild(label);edgeElements.set(id,{visible,hit,label});updateEdgeElement(e)}
function updateEdgeElement(e){const id=edgeId(e),els=edgeElements.get(id);if(!els)return;const d=curve(e);els.visible.setAttribute('d',d);els.hit.setAttribute('d',d);els.visible.classList.toggle('causal',e.causal===true);els.visible.classList.toggle('noncausal',e.causal===false);els.visible.dataset.source=e.source;els.visible.dataset.target=e.target;els.visible.dataset.relation=String(e.relation||'').toLowerCase();const a=anchor(e.source,true),b=anchor(e.target,false);els.label.setAttribute('x',(a.x+b.x)/2);els.label.setAttribute('y',(a.y+b.y)/2-6);els.label.textContent=e.count>1?`${e.relation} ×${e.count}`:e.relation}
function renderSnapshot(){leaveProtectiveMode();fullLayout();edgeLayer.replaceChildren();labelLayer.replaceChildren();nodeLayer.replaceChildren();nodeElements=new Map();edgeElements=new Map();for(const e of edgeById.values())createEdgeElement(e);for(const n of nodeById.values())createNodeElement(n);applySearch()}
function refreshEdgeLabels(){for(const e of edgeById.values())updateEdgeElement(e)}
function setSnapshot(data){graph=data;nodeById=new Map((data.nodes||[]).map(n=>[n.id,n]));edgeById=new Map((data.edges||[]).map(e=>[edgeId(e),e]));rebuildAdjacency();const signature=`${data.node_count||0}:${data.edge_count||0}`;lastSignature=signature;updateStats(data);if(!withinRenderBudget(data)){enterProtectiveMode(data);return}renderSnapshot();if(!hasFitted&&positions.size){fit();hasFitted=true}}
function mergeById(items,target,isEdge=false){const added=[];for(const item of items||[]){const id=isEdge?edgeId(item):item.id;target.set(id,item);added.push(id);if(isEdge)registerEdgeAdjacency(item)}return added}
function applyDelta(update){updateStats(update);if(update.live_payload_compact||!withinRenderBudget(update)){enterProtectiveMode(update);return}if(protectedMode){liveSequence=-1;return}const addedNodeIds=mergeById(update.nodes_added,nodeById,false);mergeById(update.nodes_updated,nodeById,false);const addedEdgeIds=mergeById(update.edges_added,edgeById,true);mergeById(update.edges_updated,edgeById,true);graph={...graph,event_count:update.event_count,node_count:update.node_count,edge_count:update.edge_count,nodes:[...nodeById.values()],edges:[...edgeById.values()]};placeAddedNodes(addedNodeIds);for(const id of addedNodeIds)createNodeElement(nodeById.get(id));for(const n of update.nodes_updated||[])updateNodeElement(n);for(const id of addedEdgeIds)createEdgeElement(edgeById.get(id));for(const e of update.edges_updated||[])updateEdgeElement(e);applySearch();if(!hasFitted&&positions.size){fit();hasFitted=true}}
function applyTransform(){viewport.setAttribute('transform',`translate(${transform.x} ${transform.y}) scale(${transform.scale})`)}
function fit(){if(!positions.size)return;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;positions.forEach(p=>{if(p.x<minX)minX=p.x;if(p.x>maxX)maxX=p.x;if(p.y<minY)minY=p.y;if(p.y>maxY)maxY=p.y});maxX+=160;maxY+=50;const box=svg.getBoundingClientRect(),w=Math.max(1,maxX-minX),h=Math.max(1,maxY-minY),scale=Math.min(1.2,Math.max(.07,Math.min((box.width-60)/w,(box.height-60)/h)));transform={x:30-minX*scale,y:30-minY*scale,scale};applyTransform()}
function applySearch(){const q=search.value.trim().toLowerCase(),matched=new Set();document.querySelectorAll('.node').forEach(el=>{const ok=!q||el.dataset.search.includes(q);el.classList.toggle('dim',!ok);if(ok)matched.add(el.dataset.id)});document.querySelectorAll('.edge').forEach(el=>{const keep=!q||matched.has(el.dataset.source)||matched.has(el.dataset.target)||el.dataset.relation.includes(q);el.classList.toggle('dim',!keep)})}
async function poll(){try{const response=await fetch(`/live.json?after=${liveSequence}`,{cache:'no-store'});if(!response.ok)throw new Error(String(response.status));const data=await response.json();if(data.kind==='snapshot'){liveSequence=Number(data.sequence)||0;setSnapshot(data.graph||{});}else if(data.kind==='delta'){if(Number(data.base_sequence)!==liveSequence){liveSequence=-1;status.textContent='RESYNCING';setTimeout(poll,0);return}for(const update of data.updates||[]){if(Number(update.sequence)!==liveSequence+1){liveSequence=-1;status.textContent='RESYNCING';setTimeout(poll,0);return}applyDelta(update);liveSequence=Number(update.sequence)}if(!(data.updates||[]).length)liveSequence=Number(data.sequence)||liveSequence;}else if(data.kind==='noop'){liveSequence=Number(data.sequence)||liveSequence;updateStats(data);}const finished=!!data.live_finished;status.textContent=finished?'FINISHED':(protectedMode?'PROTECTED':'LIVE');if(finished){setTimeout(()=>{location.href='/final'},250);return}}catch(_){status.textContent='RECONNECTING'}setTimeout(poll,500)}
svg.onpointerdown=e=>{if(e.target.closest?.('.node'))return;pan={x:e.clientX,y:e.clientY,tx:transform.x,ty:transform.y};svg.classList.add('panning');svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{if(!pan)return;transform.x=pan.tx+e.clientX-pan.x;transform.y=pan.ty+e.clientY-pan.y;applyTransform()};svg.onpointerup=e=>{pan=null;svg.classList.remove('panning');try{svg.releasePointerCapture(e.pointerId)}catch(_){}};svg.addEventListener('wheel',e=>{e.preventDefault();const rect=svg.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top,old=transform.scale,next=Math.min(4,Math.max(.07,old*Math.exp(-e.deltaY*.0012))),gx=(mx-transform.x)/old,gy=(my-transform.y)/old;transform.scale=next;transform.x=mx-gx*next;transform.y=my-gy*next;applyTransform()},{passive:false});search.oninput=applySearch;document.getElementById('fit').onclick=fit;window.onresize=()=>{if(hasFitted)fit()};applyTransform();poll();
})();
</script>
</body>
</html>"""
