from __future__ import annotations

_TREE_CSS = r""".execweave-conversation-agent-list{display:grid;gap:12px}.execweave-conversation-agent-section{padding:9px;border:1px solid var(--border);border-radius:9px;background:var(--panel2)}.execweave-conversation-agent-scope{font-size:10px;font-weight:700;color:var(--muted);letter-spacing:.03em;margin-bottom:6px;overflow-wrap:anywhere}
.execweave-conversation-tree{display:grid;gap:7px}
.execweave-conversation-root-node,.execweave-conversation-agent-node{display:flex;align-items:center;gap:7px;min-width:0;font-size:11px;font-weight:750;color:var(--text)}
.execweave-conversation-root-node::before,.execweave-conversation-agent-node::before{content:"";width:8px;height:8px;flex:0 0 8px;border-radius:50%;background:var(--selected);box-shadow:0 0 0 3px color-mix(in srgb,var(--selected) 16%,transparent)}
.execweave-conversation-root-node{padding:7px 8px;border:1px solid color-mix(in srgb,var(--selected) 35%,var(--border));border-radius:8px;background:color-mix(in srgb,var(--panel2) 92%,var(--selected) 8%)}
.execweave-conversation-agent-node{padding:4px 2px}.execweave-conversation-agent-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.execweave-conversation-agent-badge{margin-left:auto;color:var(--muted);font-size:8px;font-weight:650;text-transform:uppercase;letter-spacing:.08em}
.execweave-conversation-children{display:grid;gap:9px;margin-left:12px;padding:2px 0 2px 13px;border-left:1px solid var(--border)}
.execweave-conversation-branch{position:relative}.execweave-conversation-branch::before{content:"";position:absolute;left:-14px;top:10px;width:10px;border-top:1px solid var(--border)}
.execweave-conversation-thread{margin-top:5px;padding:6px 7px 7px 10px;border-radius:7px;background:color-mix(in srgb,var(--panel2) 72%,transparent)}
.execweave-conversation-thread>.execweave-conversation-meta,.execweave-conversation-thread>.conversation-live-meta{margin-top:0}
.execweave-conversation-tree .execweave-conversation-messages,.execweave-conversation-tree .conversation-live-messages{margin-top:6px}
.execweave-conversation-focus{display:flex;align-items:center;gap:8px;margin-bottom:8px;padding:6px 8px;border:1px solid color-mix(in srgb,var(--selected) 40%,var(--border));border-radius:7px;background:color-mix(in srgb,var(--panel2) 82%,var(--selected) 10%)}
.execweave-conversation-focus-label{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;font-weight:750;color:var(--text)}
.execweave-conversation-focus-clear{margin-left:auto;flex:0 0 auto;padding:3px 8px;border:1px solid var(--border);border-radius:6px;background:var(--panel);color:var(--text);font:inherit;font-size:9px;font-weight:650;letter-spacing:.06em;text-transform:uppercase;cursor:pointer}
.execweave-conversation-focus-clear:hover{border-color:var(--selected)}
.execweave-conversation-focus-clear:focus-visible{outline:2px solid var(--selected);outline-offset:2px}
""".strip()

_STATIC_HELPERS = r"""
const execweaveConversationRootIds=new Set(['agent:Claude Code','agent:OpenAI Codex','agent:Codex','agent:Cursor','agent:OpenCode','agent:Gemini CLI','agent:Antigravity']);
function execweaveConversationPath(entry){const p=entry?.conversation_preview||{},path=String(p.agent_path||'').trim();return path||String(entry?.source_name||entry?.source_id||'agent')}
function execweaveConversationRecordFromEntry(entry){const p=entry?.conversation_preview||{},path=execweaveConversationPath(entry),thread=String(p.thread_id||`${entry?.provider||'provider'}:${entry?.source_id||path}`),parent=p.parent_thread_id?String(p.parent_thread_id):null,label=String(p.agent_label||p.provider_label||entry?.source_name||path),isRoot=p.is_root===true||path==='/root';return{key:`thread:${thread}`,thread,parent,path,label,provider:String(entry?.provider||''),entry,isRoot,nodeId:String(entry?.source_id||'')}}
function execweaveConversationMessageCount(record){return(execweaveOwnConversationEntry(record)?.conversation_preview?.messages||[]).length}
function execweaveConversationAgentRecords(threads){const records=new Map(),byNode=new Map();for(const entry of threads){const record=execweaveConversationRecordFromEntry(entry);const node=record.nodeId;if(node){const seen=byNode.get(node);if(seen){if(execweaveConversationMessageCount(record)<=execweaveConversationMessageCount(seen))continue;records.delete(seen.key)}byNode.set(node,record)}records.set(record.key,record)}for(const node of(Array.isArray(possibleNodes)?possibleNodes:[])){if(node?.type!=='agent'||!node.id)continue;const attrs=node.attributes||{},provider=String(attrs.provider||'').toLowerCase(),agentPath=String(attrs.agent_path||attrs.child_agent_path||attrs.root_agent_path||'').trim(),isRoot=execweaveConversationRootIds.has(node.id),nativeId=String(attrs.agent_id||attrs.subagent_id||attrs.session_id||''),path=agentPath||(isRoot?'/root':nativeId?`/root/${nativeId}`:''),thread=String(attrs.thread_id||attrs.session_id||node.id),key=`graph:${node.id}`;if([...records.values()].some(record=>record.path&&path&&record.path===path&&record.provider===provider))continue;records.set(key,{key,thread,parent:null,path,label:String(node.name||path||node.id),provider,entry:null,isRoot,nodeId:String(node.id)})}return[...records.values()]}
function execweaveConversationRootRecord(records){return records.find(record=>record.isRoot)||records.find(record=>record.path==='/root')||null}
function execweaveAppendTreeConversationMessage(container,message,currentPath){const row=document.createElement('div');row.className='execweave-conversation-message';if(message?.phase==='final_answer')row.classList.add('final');if(message?.content_state==='provider_encrypted')row.classList.add('encrypted');const meta=document.createElement('div');meta.className='execweave-conversation-message-meta';const sender=String(message?.sender||''),recipient=String(message?.recipient||''),kind=String(message?.kind||'message'),phase=message?.phase?String(message.phase):'',route=recipient?`${sender||currentPath} → ${recipient}`:(sender&&sender!==currentPath?sender:'');meta.textContent=[route,kind,phase].filter(Boolean).join(' · ');const body=document.createElement('div');body.className='execweave-conversation-message-body';body.textContent=message?.content_state==='provider_encrypted'?'Provider-encrypted payload — plaintext is not exposed by the observed provider surface.':String(message?.text||'(no plaintext body exposed)');row.append(meta,body);container.appendChild(row)}
function execweaveConversationThread(entry,path){const preview=entry.conversation_preview||{},thread=document.createElement('div');thread.className='execweave-conversation-thread';const meta=document.createElement('div');meta.className='execweave-conversation-meta';meta.textContent=`${preview.provider_label||entry.provider||'provider'} · ${entry.relation||'conversation'} · ${entry.size_bytes||0} bytes`;const messages=document.createElement('div');messages.className='execweave-conversation-messages';for(const message of(preview.messages||[]).slice(-40))execweaveAppendTreeConversationMessage(messages,message,path);const raw=document.createElement('a');raw.className='execweave-conversation-link';raw.href=execweaveConversationHref(String(entry.path||''));raw.target='_blank';raw.rel='noreferrer';raw.textContent='Open raw conversation evidence';thread.append(meta,messages,raw);return thread}
function execweaveConversationAgentNode(record,isRoot=false){const node=document.createElement('div');node.className=isRoot?'execweave-conversation-root-node':'execweave-conversation-agent-node';const label=document.createElement('span');label.className='execweave-conversation-agent-label';const nickname=record.entry?.conversation_preview?.agent_nickname;label.textContent=`${record.label||record.path||record.key}${nickname&&nickname!==record.label?` · ${nickname}`:''}`;const badge=document.createElement('span');badge.className='execweave-conversation-agent-badge';badge.textContent=isRoot?'run root':record.entry?'agent':'agent · waiting';node.append(label,badge);return node}
function execweaveAppendConversationBranch(container,record,records,rootThread,visited){if(visited.has(record.key))return;visited.add(record.key);const branch=document.createElement('div');branch.className='execweave-conversation-branch';branch.appendChild(execweaveConversationAgentNode(record,false));if(record.entry)branch.appendChild(execweaveConversationThread(record.entry,record.path||record.label));const children=records.filter(candidate=>candidate.key!==record.key&&!visited.has(candidate.key)&&candidate.parent&&String(candidate.parent)===String(record.thread));if(children.length){const box=document.createElement('div');box.className='execweave-conversation-children';for(const child of children)execweaveAppendConversationBranch(box,child,records,rootThread,visited);branch.appendChild(box)}container.appendChild(branch)}
let execweaveConversationFocusNodeId=null;
function execweaveConversationFocusRecord(records){if(!execweaveConversationFocusNodeId)return null;return records.find(record=>record.nodeId&&String(record.nodeId)===String(execweaveConversationFocusNodeId))||null}
function execweaveFocusConversationAgent(node){const id=node&&node.type==='agent'&&node.id?String(node.id):null;if(execweaveConversationFocusNodeId===id)return;execweaveConversationFocusNodeId=id;execweaveRenderConversationRecords()}
function execweaveClearConversationFocus(){if(execweaveConversationFocusNodeId===null)return;execweaveConversationFocusNodeId=null;execweaveRenderConversationRecords()}
function execweaveOwnConversationMessage(message,path){const own=String(path),sender=String(message?.sender||'').trim(),recipient=String(message?.recipient||'').trim();if(!sender&&!recipient)return true;if(sender===own||recipient===own)return true;if(sender.startsWith('/')||recipient.startsWith('/'))return false;return true}
function execweaveOwnConversationEntry(record){const entry=record.entry;if(!entry)return null;const preview=entry.conversation_preview||{},path=record.path||record.label,messages=(preview.messages||[]).filter(message=>execweaveOwnConversationMessage(message,path));return{...entry,conversation_preview:{...preview,messages}}}
function execweaveOrderedConversationRecords(records){const root=records.filter(record=>record.isRoot===true||record.path==='/root'),rest=records.filter(record=>!(record.isRoot===true||record.path==='/root'));rest.sort((a,b)=>String(a.path||a.label).localeCompare(String(b.path||b.label)));return[...root,...rest]}
function execweaveConversationAgentSection(record){const section=document.createElement('section');section.className='execweave-conversation-agent-section';const count=execweaveConversationMessageCount(record);const head=document.createElement('div');head.className='execweave-conversation-agent-scope';head.textContent=`${record.path||record.label} · ${count} visible item${count===1?'':'s'}${record.parent?'':''}`;section.appendChild(head);section.appendChild(execweaveConversationAgentNode(record,record.isRoot===true));const own=execweaveOwnConversationEntry(record);if(own)section.appendChild(execweaveConversationThread(own,record.path||record.label));else{const empty=document.createElement('div');empty.className='execweave-conversation-summary';empty.textContent='No conversation evidence is available for this agent.';section.appendChild(empty)}return section}
function execweaveRenderFocusedConversation(panel,record){const banner=document.createElement('div');banner.className='execweave-conversation-focus';const label=document.createElement('span');label.className='execweave-conversation-focus-label';const count=(record.entry?.conversation_preview?.messages||[]).length;label.textContent=`${record.path||record.label} · ${count} visible item${count===1?'':'s'}`;const clear=document.createElement('button');clear.type='button';clear.className='execweave-conversation-focus-clear';clear.textContent='Show all agents';clear.addEventListener('click',execweaveClearConversationFocus);banner.append(label,clear);panel.appendChild(banner);const tree=document.createElement('div');tree.className='execweave-conversation-tree';tree.appendChild(execweaveConversationAgentNode(record,record.isRoot===true));const own=execweaveOwnConversationEntry(record);if(own)tree.appendChild(execweaveConversationThread(own,record.path||record.label));else{const empty=document.createElement('div');empty.className='execweave-conversation-summary';empty.textContent='No conversation evidence is available for this agent.';tree.appendChild(empty)}panel.appendChild(tree)}
""".strip()

_STATIC_RENDER = r"""function execweaveRenderRichConversationRecords(panel,entries){const threads=execweaveLatestConversationThreads(entries),records=execweaveConversationAgentRecords(threads);if(!threads.length&&!records.length)return false;panel.replaceChildren();const focused=execweaveConversationFocusRecord(records);if(focused){execweaveRenderFocusedConversation(panel,focused);return true}const ordered=execweaveOrderedConversationRecords(records),messageCount=ordered.reduce((total,record)=>total+execweaveConversationMessageCount(record),0),summary=document.createElement('div');summary.className='execweave-conversation-summary';summary.textContent=`${ordered.length} agent${ordered.length===1?'':'s'} · ${messageCount} visible item${messageCount===1?'':'s'} · provider-neutral run-local evidence · each agent shows only its own conversation`;panel.appendChild(summary);if(!execweaveConversationRootRecord(records)){const notice=document.createElement('div');notice.className='execweave-conversation-unresolved-root';notice.textContent='No root agent identified in this run’s evidence. Agent conversations are listed without a parent.';panel.appendChild(notice)}const list=document.createElement('div');list.className='execweave-conversation-agent-list';for(const record of ordered)list.appendChild(execweaveConversationAgentSection(record));panel.appendChild(list);const index=document.createElement('a');index.className='execweave-conversation-index';index.href=location.protocol==='file:'?'conversations.md':`/conversations.md${window.__execweaveToken?`?t=${encodeURIComponent(window.__execweaveToken)}`:''}`;index.target='_blank';index.rel='noreferrer';index.textContent='Open complete conversation index';panel.appendChild(index);return true}""".strip()

_LIVE_HELPERS = r"""
const conversationRootIds=new Set(['agent:Claude Code','agent:OpenAI Codex','agent:Codex','agent:Cursor','agent:OpenCode','agent:Gemini CLI','agent:Antigravity']);
function conversationPath(entry){const p=entry?.conversation_preview||{},path=String(p.agent_path||'').trim();return path||String(entry?.source_name||entry?.source_id||'agent')}
function conversationRecordFromEntry(entry){const p=entry?.conversation_preview||{},path=conversationPath(entry),thread=String(p.thread_id||`${entry?.provider||'provider'}:${entry?.source_id||path}`),parent=p.parent_thread_id?String(p.parent_thread_id):null,label=String(p.agent_label||p.provider_label||entry?.source_name||path),isRoot=p.is_root===true||path==='/root';return{key:`thread:${thread}`,thread,parent,path,label,provider:String(entry?.provider||''),entry,isRoot,nodeId:String(entry?.source_id||'')}}
function conversationMessageCount(record){return(ownConversationEntry(record)?.conversation_preview?.messages||[]).length}
function conversationAgentRecords(threads){const records=new Map(),byNode=new Map();for(const entry of threads){const record=conversationRecordFromEntry(entry);const node=record.nodeId;if(node){const seen=byNode.get(node);if(seen){if(conversationMessageCount(record)<=conversationMessageCount(seen))continue;records.delete(seen.key)}byNode.set(node,record)}records.set(record.key,record)}const graph=core.getGraph?.()||{};for(const node of(graph.nodes||[])){if(node?.type!=='agent'||!node.id)continue;const attrs=node.attributes||{},provider=String(attrs.provider||'').toLowerCase(),agentPath=String(attrs.agent_path||attrs.child_agent_path||attrs.root_agent_path||'').trim(),isRoot=conversationRootIds.has(node.id),nativeId=String(attrs.agent_id||attrs.subagent_id||attrs.session_id||''),path=agentPath||(isRoot?'/root':nativeId?`/root/${nativeId}`:''),thread=String(attrs.thread_id||attrs.session_id||node.id),key=`graph:${node.id}`;if([...records.values()].some(record=>record.path&&path&&record.path===path&&record.provider===provider))continue;records.set(key,{key,thread,parent:null,path,label:String(node.name||path||node.id),provider,entry:null,isRoot,nodeId:String(node.id)})}return[...records.values()]}
function conversationRootRecord(records){return records.find(record=>record.isRoot)||records.find(record=>record.path==='/root')||null}
function appendTreeMessage(container,message,currentPath){const row=document.createElement('div');row.className='conversation-live-message';if(message?.phase==='final_answer')row.classList.add('final');if(message?.content_state==='provider_encrypted')row.classList.add('encrypted');const meta=document.createElement('div');meta.className='conversation-live-message-meta';const sender=String(message?.sender||''),recipient=String(message?.recipient||''),kind=String(message?.kind||'message'),phase=message?.phase?String(message.phase):'',route=recipient?`${sender||currentPath} → ${recipient}`:(sender&&sender!==currentPath?sender:'');meta.textContent=[route,kind,phase].filter(Boolean).join(' · ');const body=document.createElement('div');body.className='conversation-live-message-body';body.textContent=message?.content_state==='provider_encrypted'?'Provider-encrypted payload — plaintext is not exposed by the observed provider surface.':String(message?.text||'(no plaintext body exposed)');row.append(meta,body);container.appendChild(row)}
function conversationThread(entry,path){const preview=entry.conversation_preview||{},thread=document.createElement('div');thread.className='execweave-conversation-thread';const meta=document.createElement('div');meta.className='conversation-live-meta';meta.textContent=`${preview.provider_label||entry.provider||'provider'} · ${entry.relation||'conversation'} · ${entry.size_bytes||0} bytes`;const messages=document.createElement('div');messages.className='conversation-live-messages';for(const message of(preview.messages||[]).slice(-40))appendTreeMessage(messages,message,path);const raw=document.createElement('a');raw.className='conversation-live-link';raw.href=href(String(entry.path||''));raw.target='_blank';raw.rel='noreferrer';raw.textContent='Open raw conversation evidence';thread.append(meta,messages,raw);return thread}
function conversationAgentNode(record,isRoot=false){const node=document.createElement('div');node.className=isRoot?'execweave-conversation-root-node':'execweave-conversation-agent-node';const label=document.createElement('span');label.className='execweave-conversation-agent-label';const nickname=record.entry?.conversation_preview?.agent_nickname;label.textContent=`${record.label||record.path||record.key}${nickname&&nickname!==record.label?` · ${nickname}`:''}`;const badge=document.createElement('span');badge.className='execweave-conversation-agent-badge';badge.textContent=isRoot?'run root':record.entry?'agent':'agent · waiting';node.append(label,badge);return node}
function appendConversationBranch(container,record,records,visited){if(visited.has(record.key))return;visited.add(record.key);const branch=document.createElement('div');branch.className='execweave-conversation-branch';branch.appendChild(conversationAgentNode(record,false));if(record.entry)branch.appendChild(conversationThread(record.entry,record.path||record.label));const direct=records.filter(candidate=>candidate.key!==record.key&&!visited.has(candidate.key)&&candidate.parent&&String(candidate.parent)===String(record.thread));if(direct.length){const box=document.createElement('div');box.className='execweave-conversation-children';for(const child of direct)appendConversationBranch(box,child,records,visited);branch.appendChild(box)}container.appendChild(branch)}
let conversationFocusNodeId=null;
function conversationFocusRecord(records){if(!conversationFocusNodeId)return null;return records.find(record=>record.nodeId&&String(record.nodeId)===String(conversationFocusNodeId))||null}
function focusConversationAgent(node){const id=node&&node.type==='agent'&&node.id?String(node.id):null;if(conversationFocusNodeId===id)return;conversationFocusNodeId=id;render()}
function clearConversationFocus(){if(conversationFocusNodeId===null)return;conversationFocusNodeId=null;render()}
function ownConversationMessage(message,path){const own=String(path),sender=String(message?.sender||'').trim(),recipient=String(message?.recipient||'').trim();if(!sender&&!recipient)return true;if(sender===own||recipient===own)return true;if(sender.startsWith('/')||recipient.startsWith('/'))return false;return true}
function ownConversationEntry(record){const entry=record.entry;if(!entry)return null;const preview=entry.conversation_preview||{},path=record.path||record.label,messages=(preview.messages||[]).filter(message=>ownConversationMessage(message,path));return{...entry,conversation_preview:{...preview,messages}}}
function orderedConversationRecords(records){const root=records.filter(record=>record.isRoot===true||record.path==='/root'),rest=records.filter(record=>!(record.isRoot===true||record.path==='/root'));rest.sort((a,b)=>String(a.path||a.label).localeCompare(String(b.path||b.label)));return[...root,...rest]}
function conversationAgentSection(record){const section=document.createElement('section');section.className='execweave-conversation-agent-section';const count=conversationMessageCount(record);const head=document.createElement('div');head.className='execweave-conversation-agent-scope';head.textContent=`${record.path||record.label} · ${count} visible item${count===1?'':'s'}`;section.appendChild(head);section.appendChild(conversationAgentNode(record,record.isRoot===true));const own=ownConversationEntry(record);if(own)section.appendChild(conversationThread(own,record.path||record.label));else{const empty=document.createElement('div');empty.className='conversation-live-summary';empty.textContent='No conversation evidence is available for this agent.';section.appendChild(empty)}return section}
function renderFocusedConversation(panel,record){const banner=document.createElement('div');banner.className='execweave-conversation-focus';const label=document.createElement('span');label.className='execweave-conversation-focus-label';const count=(record.entry?.conversation_preview?.messages||[]).length;label.textContent=`${record.path||record.label} · ${count} visible item${count===1?'':'s'}`;const clear=document.createElement('button');clear.type='button';clear.className='execweave-conversation-focus-clear';clear.textContent='Show all agents';clear.addEventListener('click',clearConversationFocus);banner.append(label,clear);panel.appendChild(banner);const tree=document.createElement('div');tree.className='execweave-conversation-tree';tree.appendChild(conversationAgentNode(record,record.isRoot===true));const own=ownConversationEntry(record);if(own)tree.appendChild(conversationThread(own,record.path||record.label));else{const empty=document.createElement('div');empty.className='conversation-live-summary';empty.textContent='No conversation evidence is available for this agent.';tree.appendChild(empty)}panel.appendChild(tree)}
window.__execweaveFocusConversationAgent=focusConversationAgent;window.__execweaveClearConversationFocus=clearConversationFocus;
""".strip()

_LIVE_RENDER = r"""function renderRich(entries){const threads=latestThreads(entries),records=conversationAgentRecords(threads);if(!threads.length&&!records.length)return false;panel.replaceChildren();const focused=conversationFocusRecord(records);if(focused){renderFocusedConversation(panel,focused);return true}const ordered=orderedConversationRecords(records),count=ordered.reduce((n,record)=>n+conversationMessageCount(record),0),summary=document.createElement('div');summary.className='conversation-live-summary';summary.textContent=`${ordered.length} agent${ordered.length===1?'':'s'} · ${count} visible item${count===1?'':'s'} · provider-neutral run-local record · each agent shows only its own conversation`;panel.appendChild(summary);if(!conversationRootRecord(records)){const notice=document.createElement('div');notice.className='conversation-live-unresolved-root';notice.textContent='No root agent identified in this run’s evidence. Agent conversations are listed without a parent.';panel.appendChild(notice)}const list=document.createElement('div');list.className='execweave-conversation-agent-list';for(const record of ordered)list.appendChild(conversationAgentSection(record));panel.appendChild(list);const index=document.createElement('a');index.className='conversation-live-index';index.href=`/conversations.md${window.__execweaveToken?`?t=${encodeURIComponent(window.__execweaveToken)}`:''}`;index.target='_blank';index.rel='noreferrer';index.textContent='Open complete conversation index';panel.appendChild(index);return true}""".strip()


def _replace_between(html: str, start: str, following: str, replacement: str) -> str:
    begin = html.find(start)
    if begin < 0:
        return html
    end = html.find(following, begin)
    if end < 0:
        return html
    return html[:begin] + replacement + "\n" + html[end:]


def _neutralize_copy(html: str) -> str:
    return (
        html.replace(
            "Provider-encrypted payload — plaintext is not exposed by the Codex rollout.",
            "Provider-encrypted payload — plaintext is not exposed by the observed provider surface.",
        )
        .replace("Open run-local raw rollout evidence", "Open raw conversation evidence")
        .replace("Open raw rollout evidence", "Open raw conversation evidence")
        .replace("Codex conversation", "Conversation")
    )


def inject_standalone_conversation_tree(html: str) -> str:
    """Render provider-neutral run-local conversations as a rooted agent hierarchy."""
    html = _neutralize_copy(html)
    if "function execweaveRenderRichConversationRecords(panel,entries){" not in html:
        return html
    result = html.replace("</style>", _TREE_CSS + "\n</style>", 1)
    marker = "function execweaveRenderRichConversationRecords(panel,entries){"
    result = result.replace(marker, _STATIC_HELPERS + "\n" + marker, 1)
    return _replace_between(
        result,
        marker,
        "function execweaveRenderConversationRecords(){",
        _STATIC_RENDER,
    )


def inject_live_conversation_tree(html: str) -> str:
    """Give the live conversation panel the same provider-neutral hierarchy."""
    html = _neutralize_copy(html)
    if "function renderRich(entries){" not in html:
        return html
    result = html.replace("</style>", _TREE_CSS + "\n</style>", 1)
    marker = "function renderRich(entries){"
    result = result.replace(marker, _LIVE_HELPERS + "\n" + marker, 1)
    return _replace_between(result, marker, "async function loadIndex(){", _LIVE_RENDER)
