from pathlib import Path

CONFIG = {
    "README.md": {
        "start": "Watch Claude Code, OpenAI Codex, or Gemini CLI live:\n",
        "quick": """Live OS-runtime telemetry works with **any local command**. The names below are examples, not a whitelist:\n\n```bash\n# Agent / IDE CLIs\nexecweave live --open -- claude\nexecweave live --open -- codex\nexecweave live --open -- gemini\nexecweave live --open -- cursor\nexecweave live --open -- opencode\n\n# Any local program\nexecweave live --open -- python my_agent.py\n\n# A local model runtime launched under ExecWeave\nexecweave live --open -- ollama serve\n```\n\n`execweave live` streams process, file, and network evidence for the command tree it launches. It does **not** automatically inject Agent semantic hooks, model-runtime API metadata, or inference-gateway routing metadata into the Live Viewer.\n\n#### Live capability matrix\n\n| Integration | Direct OS-runtime live | Specialized metadata | Automatically in Live Viewer |\n| --- | --- | --- | --- |\n| Claude Code | Yes | `execweave-claude-record` / hooks | No |\n| OpenAI Codex | Yes | `execweave-codex-record` / hooks | No |\n| Gemini CLI | Yes | `execweave-gemini-record` / hooks | No |\n| Cursor | Yes | `execweave-cursor-record` / hooks | No |\n| OpenCode | Yes | `execweave-opencode-record` / plugin | No |\n| Ollama | Yes, when launched under ExecWeave (for example `ollama serve`) | `execweave-model-runtime event/probe --runtime ollama` | No |\n| llama.cpp | Yes, when its local server is launched under ExecWeave | `execweave-model-runtime event/probe --runtime llamacpp` | No |\n| vLLM | Yes, when its local server is launched under ExecWeave | `execweave-model-runtime event/probe --runtime vllm` | No |\n| LM Studio | Yes only for a local process launched under ExecWeave; an already-running server is not attached | `execweave-model-runtime event/probe --runtime lmstudio` | No |\n| LiteLLM Proxy | Yes, when the local proxy is launched under ExecWeave | `execweave-inference-gateway event --gateway litellm` | No |\n| OpenRouter | No direct remote-service process; run the local client/Agent under `live` instead | `execweave-inference-gateway event/generation --gateway openrouter` | No |\n\nFor an already-running Ollama server, use `execweave-model-runtime probe --runtime ollama` to snapshot loaded-model state. For OpenRouter, `live` can observe the local client and its network activity, while gateway routing/usage metadata remains a separate evidence layer.\n\n""",
        "old_note": "`execweave live --open -- cursor` is supported for generic runtime telemetry. For Cursor semantic hooks and conservative tool/process correlation, use `execweave-cursor-record --open -- cursor`.",
        "new_note": "`live` is a generic OS-runtime view rather than an integration whitelist. Specialized Agent semantic, model-runtime, and gateway metadata remain separate evidence layers and are not automatically injected into the Live Viewer in v0.6.3.",
    },
    "README.zh-TW.md": {
        "start": "即時觀察 Claude Code、OpenAI Codex 或 Gemini CLI：\n",
        "quick": """Live OS-runtime telemetry 可用於 **任何本機 command**；下面只是例子，不是 whitelist：\n\n```bash\n# Agent / IDE CLI\nexecweave live --open -- claude\nexecweave live --open -- codex\nexecweave live --open -- gemini\nexecweave live --open -- cursor\nexecweave live --open -- opencode\n\n# 任意本機程式\nexecweave live --open -- python my_agent.py\n\n# 由 ExecWeave 啟動的本機 model runtime\nexecweave live --open -- ollama serve\n```\n\n`execweave live` 即時呈現它所啟動 command tree 的 process、file、network evidence。Agent semantic hooks、model-runtime API metadata、inference-gateway routing metadata **目前不會自動注入 Live Viewer**。\n\n#### Live 能力矩陣\n\n| Integration | 直接 OS-runtime live | 專用 metadata | 自動進入 Live Viewer |\n| --- | --- | --- | --- |\n| Claude Code | 可以 | `execweave-claude-record` / hooks | 否 |\n| OpenAI Codex | 可以 | `execweave-codex-record` / hooks | 否 |\n| Gemini CLI | 可以 | `execweave-gemini-record` / hooks | 否 |\n| Cursor | 可以 | `execweave-cursor-record` / hooks | 否 |\n| OpenCode | 可以 | `execweave-opencode-record` / plugin | 否 |\n| Ollama | 可以，但需由 ExecWeave 啟動，例如 `ollama serve` | `execweave-model-runtime event/probe --runtime ollama` | 否 |\n| llama.cpp | 可以，但需由 ExecWeave 啟動本機 server | `execweave-model-runtime event/probe --runtime llamacpp` | 否 |\n| vLLM | 可以，但需由 ExecWeave 啟動本機 server | `execweave-model-runtime event/probe --runtime vllm` | 否 |\n| LM Studio | 只有由 ExecWeave 啟動的本機 process；不會 attach 已在執行的 server | `execweave-model-runtime event/probe --runtime lmstudio` | 否 |\n| LiteLLM Proxy | 可以，但需由 ExecWeave 啟動本機 proxy | `execweave-inference-gateway event --gateway litellm` | 否 |\n| OpenRouter | 遠端服務本身不能直接 live；請 live 本機 client/Agent | `execweave-inference-gateway event/generation --gateway openrouter` | 否 |\n\n若 Ollama 已經在背景執行，可用 `execweave-model-runtime probe --runtime ollama` snapshot 目前 loaded-model state。OpenRouter 則可由 `live` 觀察本機 client 與 network activity，而 gateway routing/usage metadata 仍保持為獨立 evidence layer。\n\n""",
        "old_note": "`execweave live --open -- cursor` 可用於通用 runtime telemetry；若需要 Cursor semantic hooks 與保守的 tool/process correlation，請使用 `execweave-cursor-record --open -- cursor`。",
        "new_note": "`live` 是通用 OS-runtime view，不是 integration whitelist。Agent semantic、model-runtime、gateway metadata 仍是分離的 evidence layers，在 v0.6.3 不會自動注入 Live Viewer。",
    },
    "README.zh-CN.md": {
        "start": "实时观察 Claude Code、OpenAI Codex 或 Gemini CLI：\n",
        "quick": """Live OS-runtime telemetry 可用于 **任何本地 command**；下面只是示例，不是 whitelist：\n\n```bash\n# Agent / IDE CLI\nexecweave live --open -- claude\nexecweave live --open -- codex\nexecweave live --open -- gemini\nexecweave live --open -- cursor\nexecweave live --open -- opencode\n\n# 任意本地程序\nexecweave live --open -- python my_agent.py\n\n# 由 ExecWeave 启动的本地 model runtime\nexecweave live --open -- ollama serve\n```\n\n`execweave live` 实时呈现它所启动 command tree 的 process、file、network evidence。Agent semantic hooks、model-runtime API metadata、inference-gateway routing metadata **目前不会自动注入 Live Viewer**。\n\n#### Live 能力矩阵\n\n| Integration | 直接 OS-runtime live | 专用 metadata | 自动进入 Live Viewer |\n| --- | --- | --- | --- |\n| Claude Code | 可以 | `execweave-claude-record` / hooks | 否 |\n| OpenAI Codex | 可以 | `execweave-codex-record` / hooks | 否 |\n| Gemini CLI | 可以 | `execweave-gemini-record` / hooks | 否 |\n| Cursor | 可以 | `execweave-cursor-record` / hooks | 否 |\n| OpenCode | 可以 | `execweave-opencode-record` / plugin | 否 |\n| Ollama | 可以，但需由 ExecWeave 启动，例如 `ollama serve` | `execweave-model-runtime event/probe --runtime ollama` | 否 |\n| llama.cpp | 可以，但需由 ExecWeave 启动本地 server | `execweave-model-runtime event/probe --runtime llamacpp` | 否 |\n| vLLM | 可以，但需由 ExecWeave 启动本地 server | `execweave-model-runtime event/probe --runtime vllm` | 否 |\n| LM Studio | 仅限由 ExecWeave 启动的本地 process；不会 attach 已运行的 server | `execweave-model-runtime event/probe --runtime lmstudio` | 否 |\n| LiteLLM Proxy | 可以，但需由 ExecWeave 启动本地 proxy | `execweave-inference-gateway event --gateway litellm` | 否 |\n| OpenRouter | 远程服务本身不能直接 live；请 live 本地 client/Agent | `execweave-inference-gateway event/generation --gateway openrouter` | 否 |\n\n如果 Ollama 已在后台运行，可用 `execweave-model-runtime probe --runtime ollama` snapshot 当前 loaded-model state。OpenRouter 可由 `live` 观察本地 client 与 network activity，而 gateway routing/usage metadata 仍保持为独立 evidence layer。\n\n""",
        "old_note": "`execweave live --open -- cursor` 可用于通用 runtime telemetry；如需 Cursor semantic hooks 与保守的 tool/process correlation，请使用 `execweave-cursor-record --open -- cursor`。",
        "new_note": "`live` 是通用 OS-runtime view，不是 integration whitelist。Agent semantic、model-runtime、gateway metadata 仍是分离的 evidence layers，在 v0.6.3 不会自动注入 Live Viewer。",
    },
    "README.ja.md": {
        "start": "Claude Code、OpenAI Codex、Gemini CLI をライブで観察：\n",
        "quick": """Live OS-runtime telemetry は **任意のローカル command** に使用できます。以下は whitelist ではなく例です：\n\n```bash\n# Agent / IDE CLI\nexecweave live --open -- claude\nexecweave live --open -- codex\nexecweave live --open -- gemini\nexecweave live --open -- cursor\nexecweave live --open -- opencode\n\n# 任意のローカルプログラム\nexecweave live --open -- python my_agent.py\n\n# ExecWeave から起動するローカル model runtime\nexecweave live --open -- ollama serve\n```\n\n`execweave live` は、起動した command tree の process / file / network evidence をリアルタイム表示します。Agent semantic hooks、model-runtime API metadata、inference-gateway routing metadata は **現在 Live Viewer に自動注入されません**。\n\n#### Live capability matrix\n\n| Integration | Direct OS-runtime live | Specialized metadata | Auto in Live Viewer |\n| --- | --- | --- | --- |\n| Claude Code | Yes | `execweave-claude-record` / hooks | No |\n| OpenAI Codex | Yes | `execweave-codex-record` / hooks | No |\n| Gemini CLI | Yes | `execweave-gemini-record` / hooks | No |\n| Cursor | Yes | `execweave-cursor-record` / hooks | No |\n| OpenCode | Yes | `execweave-opencode-record` / plugin | No |\n| Ollama | Yes, ExecWeave から起動する場合（例: `ollama serve`） | `execweave-model-runtime event/probe --runtime ollama` | No |\n| llama.cpp | Yes, ローカル server を ExecWeave から起動する場合 | `execweave-model-runtime event/probe --runtime llamacpp` | No |\n| vLLM | Yes, ローカル server を ExecWeave から起動する場合 | `execweave-model-runtime event/probe --runtime vllm` | No |\n| LM Studio | ExecWeave から起動したローカル process のみ。既存 server には attach しません | `execweave-model-runtime event/probe --runtime lmstudio` | No |\n| LiteLLM Proxy | Yes, ローカル proxy を ExecWeave から起動する場合 | `execweave-inference-gateway event --gateway litellm` | No |\n| OpenRouter | Remote service 自体は direct live 不可。ローカル client/Agent を live してください | `execweave-inference-gateway event/generation --gateway openrouter` | No |\n\nOllama がすでにバックグラウンドで動作中なら、`execweave-model-runtime probe --runtime ollama` で loaded-model state を snapshot できます。OpenRouter では `live` がローカル client と network activity を観測し、gateway routing/usage metadata は別の evidence layer のままです。\n\n""",
        "old_note": "`execweave live --open -- cursor` は汎用 runtime telemetry に対応します。Cursor semantic hooks と保守的な tool/process correlation が必要な場合は `execweave-cursor-record --open -- cursor` を使用してください。",
        "new_note": "`live` は汎用 OS-runtime view であり integration whitelist ではありません。Agent semantic、model-runtime、gateway metadata は分離された evidence layer のままで、v0.6.3 では Live Viewer に自動注入されません。",
    },
    "README.ko.md": {
        "start": "Claude Code, OpenAI Codex 또는 Gemini CLI를 실시간으로 관찰:\n",
        "quick": """Live OS-runtime telemetry는 **모든 로컬 command**에 사용할 수 있습니다. 아래 항목은 whitelist가 아니라 예시입니다:\n\n```bash\n# Agent / IDE CLI\nexecweave live --open -- claude\nexecweave live --open -- codex\nexecweave live --open -- gemini\nexecweave live --open -- cursor\nexecweave live --open -- opencode\n\n# 임의의 로컬 프로그램\nexecweave live --open -- python my_agent.py\n\n# ExecWeave가 시작하는 로컬 model runtime\nexecweave live --open -- ollama serve\n```\n\n`execweave live`는 자신이 시작한 command tree의 process, file, network evidence를 실시간으로 보여 줍니다. Agent semantic hooks, model-runtime API metadata, inference-gateway routing metadata는 **현재 Live Viewer에 자동으로 주입되지 않습니다**.\n\n#### Live capability matrix\n\n| Integration | Direct OS-runtime live | Specialized metadata | Auto in Live Viewer |\n| --- | --- | --- | --- |\n| Claude Code | Yes | `execweave-claude-record` / hooks | No |\n| OpenAI Codex | Yes | `execweave-codex-record` / hooks | No |\n| Gemini CLI | Yes | `execweave-gemini-record` / hooks | No |\n| Cursor | Yes | `execweave-cursor-record` / hooks | No |\n| OpenCode | Yes | `execweave-opencode-record` / plugin | No |\n| Ollama | Yes, ExecWeave가 시작한 경우(예: `ollama serve`) | `execweave-model-runtime event/probe --runtime ollama` | No |\n| llama.cpp | Yes, 로컬 server를 ExecWeave가 시작한 경우 | `execweave-model-runtime event/probe --runtime llamacpp` | No |\n| vLLM | Yes, 로컬 server를 ExecWeave가 시작한 경우 | `execweave-model-runtime event/probe --runtime vllm` | No |\n| LM Studio | ExecWeave가 시작한 로컬 process만 가능하며 기존 server에는 attach하지 않음 | `execweave-model-runtime event/probe --runtime lmstudio` | No |\n| LiteLLM Proxy | Yes, 로컬 proxy를 ExecWeave가 시작한 경우 | `execweave-inference-gateway event --gateway litellm` | No |\n| OpenRouter | Remote service 자체는 direct live 불가. 로컬 client/Agent를 live해야 함 | `execweave-inference-gateway event/generation --gateway openrouter` | No |\n\nOllama가 이미 백그라운드에서 실행 중이면 `execweave-model-runtime probe --runtime ollama`로 loaded-model state를 snapshot할 수 있습니다. OpenRouter에서는 `live`가 로컬 client와 network activity를 관측하고 gateway routing/usage metadata는 별도 evidence layer로 유지됩니다.\n\n""",
        "old_note": "`execweave live --open -- cursor`는 일반 runtime telemetry에 사용할 수 있습니다. Cursor semantic hooks와 보수적인 tool/process correlation이 필요하면 `execweave-cursor-record --open -- cursor`를 사용하세요.",
        "new_note": "`live`는 일반 OS-runtime view이며 integration whitelist가 아닙니다. Agent semantic, model-runtime, gateway metadata는 분리된 evidence layer로 유지되며 v0.6.3에서는 Live Viewer에 자동으로 주입되지 않습니다.",
    },
}

MARKER = "<!-- v0.6.3-live -->"

for filename, cfg in CONFIG.items():
    path = Path(filename)
    text = path.read_text(encoding="utf-8")
    start = text.find(cfg["start"])
    marker = text.find(MARKER)
    if start < 0 or marker < 0 or marker <= start:
        raise SystemExit(f"quick-start markers not found in {filename}")
    text = text[:start] + cfg["quick"] + text[marker:]
    if cfg["old_note"] not in text:
        raise SystemExit(f"live note not found in {filename}")
    text = text.replace(cfg["old_note"], cfg["new_note"], 1)
    path.write_text(text, encoding="utf-8")
